/**
 * Agentic Bitcoin design tokens — the single source of truth.
 *
 * Values are the ones measured on instinct.com on 2026-10-07 (see plan.md "Reference: what
 * instinct.com actually is"). We copy structure, spacing and interaction; fonts, logo and copy
 * are our own (ADR-0002).
 *
 * The browser consumes the generated `tokens.css` (run `pnpm --filter @agentic-bitcoin/brand build`).
 * JS/TS consumers import this module directly. Never hand-edit `tokens.css`.
 */

export const tokens = {
  color: {
    /** Outer page / html background. */
    sand100: "#f4efec",
    /** Thick CTA underline, reaction bubble. */
    sand400: "#e1d5cd",
    /** CTA underline on hover. */
    sand500: "#d3c3b8",
    /** Inner page (the white card). */
    ivory500: "#fdfcfb",
    paper: "#ffffff",
    /** Body text. */
    onyx450: "#1f2322",
    soot200: "#969394",
    soot400: "#585254",
    accentRed: "#ed313e",
    accentTeal: "#73a89a",
    /** Bitcoin orange — used only in the reaction icons, never for text. */
    bitcoin: "#f7931a",
    /** Task underline at rest: onyx at 20%. */
    taskUnderline: "rgba(31, 35, 34, 0.2)",
  },
  font: {
    // --font-newsreader / --font-inter are injected by next/font in the app layout (ADR-0003).
    // They must NOT share a name with these tokens: both land on :root, and a self-reference
    // makes the whole declaration invalid (we shipped Times for ten minutes that way).
    serif: "var(--font-newsreader, ui-serif), Georgia, 'Times New Roman', serif",
    sans: "var(--font-inter, ui-sans-serif), system-ui, -apple-system, sans-serif",
    mono: "ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
  },
  type: {
    /** Instinct home: one size for the whole intro. */
    homeSize: "24px",
    homeLeading: "130%",
    homeTracking: "-0.01em",
    legalSize: "13px",
    legalLeading: "102%",
  },
  space: {
    xs: "8px",
    sml: "12px",
    reg: "16px",
    xl: "20px",
    "2xl": "24px",
    "3xl": "32px",
    "4xl": "40px",
    "6xl": "64px",
    "8xl": "96px",
  },
  layout: {
    introMaxWidth: "41rem",
    logoWidth: "28px",
    logoWidthWide: "34px",
    reactionSize: "35.6px",
    reactionIcon: "20px",
  },
  motion: {
    /** The spring curve instinct.com uses for the reaction pop. */
    easePop:
      "linear(0, .092, .296, .528, .736, .897, 1.004, 1.063, 1.085, 1.084, 1.068, 1.049, 1.029, 1.014, 1.003, .996, .993, .993, .993, .995, .997, .998, .999, 1)",
    easeReveal: "cubic-bezier(.22, 1, .36, 1)",
    revealDuration: "0.6s",
    revealStagger: "90ms",
  },
} as const

export type Tokens = typeof tokens

/** Flatten the token tree into CSS custom properties, e.g. `--color-sand-400: #e1d5cd;`. */
export function tokensToCssVars(t: Tokens = tokens): Record<string, string> {
  const vars: Record<string, string> = {}
  for (const [group, entries] of Object.entries(t)) {
    for (const [key, value] of Object.entries(entries as Record<string, string>)) {
      vars[`--${kebab(group)}-${kebab(key)}`] = value
    }
  }
  return vars
}

/** Render tokens as a `:root { ... }` stylesheet string. */
export function tokensToCss(t: Tokens = tokens): string {
  const vars = tokensToCssVars(t)
  const body = Object.entries(vars)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n")
  return `/* GENERATED by @agentic-bitcoin/brand — edit src/tokens.ts, then run build. */\n:root {\n${body}\n}\n`
}

function kebab(s: string): string {
  return s
    .replace(/([a-z])([0-9])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
}
